/*
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 package com.example.application.FinancialReport.entity;

 import java.util.Objects;
 import com.fasterxml.jackson.annotation.JsonProperty;
 import io.swagger.v3.oas.annotations.media.Schema;

 
 /**
  * FinancialReport
  */
 @javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2023-03-29T01:13:52.016744464Z[GMT]")public class FinancialReport   {
   @JsonProperty("title")
   private String title = null;
 
   @JsonProperty("date")
   private String date = null;
 
   @JsonProperty("type")
   private String type = null;
 
   @JsonProperty("income")
   private Integer income = null;
 
   @JsonProperty("totalSpent")
   private Integer totalSpent = null;
 
   @JsonProperty("netTotal")
   private Integer netTotal = null;
 
   public FinancialReport title(String title) {
     this.title = title;
     return this;
   }
 
   /**
    * Get title
    * @return title
    **/
   @JsonProperty("title")
   @Schema(description = "")
   public String getTitle() {
     return title;
   }
 
   public void setTitle(String title) {
     this.title = title;
   }
 
   public FinancialReport date(String date) {
     this.date = date;
     return this;
   }
 
   /**
    * Get date
    * @return date
    **/
   @JsonProperty("date")
   @Schema(description = "")
   public String getDate() {
     return date;
   }
 
   public void setDate(String date) {
     this.date = date;
   }
 
   public FinancialReport type(String type) {
     this.type = type;
     return this;
   }
 
   /**
    * Get type
    * @return type
    **/
   @JsonProperty("type")
   @Schema(description = "")
   public String getType() {
     return type;
   }
 
   public void setType(String type) {
     this.type = type;
   }
 
   public FinancialReport income(Integer income) {
     this.income = income;
     return this;
   }
 
   /**
    * Get income
    * @return income
    **/
   @JsonProperty("income")
   @Schema(description = "")
   public Integer getIncome() {
     return income;
   }
 
   public void setIncome(Integer income) {
     this.income = income;
   }
 
   public FinancialReport totalSpent(Integer totalSpent) {
     this.totalSpent = totalSpent;
     return this;
   }
 
   /**
    * Get totalSpent
    * @return totalSpent
    **/
   @JsonProperty("totalSpent")
   @Schema(description = "")
   public Integer getTotalSpent() {
     return totalSpent;
   }
 
   public void setTotalSpent(Integer totalSpent) {
     this.totalSpent = totalSpent;
   }
 
   public FinancialReport netTotal(Integer netTotal) {
     this.netTotal = netTotal;
     return this;
   }
 
   /**
    * Get netTotal
    * @return netTotal
    **/
   @JsonProperty("netTotal")
   @Schema(description = "")
   public Integer getNetTotal() {
     return netTotal;
   }
 
   public void setNetTotal(Integer netTotal) {
     this.netTotal = netTotal;
   }
 
 
   @Override
   public boolean equals(java.lang.Object o) {
     if (this == o) {
       return true;
     }
     if (o == null || getClass() != o.getClass()) {
       return false;
     }
     FinancialReport financialReport = (FinancialReport) o;
     return Objects.equals(this.title, financialReport.title) &&
         Objects.equals(this.date, financialReport.date) &&
         Objects.equals(this.type, financialReport.type) &&
         Objects.equals(this.income, financialReport.income) &&
         Objects.equals(this.totalSpent, financialReport.totalSpent) &&
         Objects.equals(this.netTotal, financialReport.netTotal);
   }
 
   @Override
   public int hashCode() {
     return Objects.hash(title, date, type, income, totalSpent, netTotal);
   }
 
 
   @Override
   public String toString() {
     StringBuilder sb = new StringBuilder();
     sb.append("class FinancialReport {\n");
     
     sb.append("    title: ").append(toIndentedString(title)).append("\n");
     sb.append("    date: ").append(toIndentedString(date)).append("\n");
     sb.append("    type: ").append(toIndentedString(type)).append("\n");
     sb.append("    income: ").append(toIndentedString(income)).append("\n");
     sb.append("    totalSpent: ").append(toIndentedString(totalSpent)).append("\n");
     sb.append("    netTotal: ").append(toIndentedString(netTotal)).append("\n");
     sb.append("}");
     return sb.toString();
   }
 
   /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
   private String toIndentedString(java.lang.Object o) {
     if (o == null) {
       return "null";
     }
     return o.toString().replace("\n", "\n    ");
   }
 }
 