/*
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.application.TrainingHistory.entity;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * TrainingHistory
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2023-03-29T01:13:52.016744464Z[GMT]")public class TrainingHistory   {
  @JsonProperty("registerDate")
  private String registerDate = null;

  @JsonProperty("course")
  private String course = null;

  @JsonProperty("completeDate")
  private String completeDate = null;

  public TrainingHistory registerDate(String registerDate) {
    this.registerDate = registerDate;
    return this;
  }

  /**
   * Get registerDate
   * @return registerDate
   **/
  @JsonProperty("registerDate")
  @Schema(description = "")
  public String getRegisterDate() {
    return registerDate;
  }

  public void setRegisterDate(String registerDate) {
    this.registerDate = registerDate;
  }

  public TrainingHistory course(String course) {
    this.course = course;
    return this;
  }

  /**
   * Get course
   * @return course
   **/
  @JsonProperty("course")
  @Schema(description = "")
  public String getCourse() {
    return course;
  }

  public void setCourse(String course) {
    this.course = course;
  }

  public TrainingHistory completeDate(String completeDate) {
    this.completeDate = completeDate;
    return this;
  }

  /**
   * Get completeDate
   * @return completeDate
   **/
  @JsonProperty("completeDate")
  @Schema(description = "")
  public String getCompleteDate() {
    return completeDate;
  }

  public void setCompleteDate(String completeDate) {
    this.completeDate = completeDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainingHistory trainingHistory = (TrainingHistory) o;
    return Objects.equals(this.registerDate, trainingHistory.registerDate) &&
        Objects.equals(this.course, trainingHistory.course) &&
        Objects.equals(this.completeDate, trainingHistory.completeDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(registerDate, course, completeDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainingHistory {\n");
    
    sb.append("    registerDate: ").append(toIndentedString(registerDate)).append("\n");
    sb.append("    course: ").append(toIndentedString(course)).append("\n");
    sb.append("    completeDate: ").append(toIndentedString(completeDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
