/*
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.application.HumanResourcesHistory.entity;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;


/**
 * HumanResourcesHistory
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2023-03-29T01:13:52.016744464Z[GMT]")public class HumanResourcesHistory   {
  @JsonProperty("hireDate")
  private String hireDate = null;

  @JsonProperty("reason")
  private String reason = null;

  @JsonProperty("leaveDate")
  private String leaveDate = null;

  public HumanResourcesHistory hireDate(String hireDate) {
    this.hireDate = hireDate;
    return this;
  }

  /**
   * Get hireDate
   * @return hireDate
   **/
  @JsonProperty("hireDate")
  @Schema(description = "")
  public String getHireDate() {
    return hireDate;
  }

  public void setHireDate(String hireDate) {
    this.hireDate = hireDate;
  }

  public HumanResourcesHistory reason(String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   **/
  @JsonProperty("reason")
  @Schema(description = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public HumanResourcesHistory leaveDate(String leaveDate) {
    this.leaveDate = leaveDate;
    return this;
  }

  /**
   * Get leaveDate
   * @return leaveDate
   **/
  @JsonProperty("leaveDate")
  @Schema(description = "")
  public String getLeaveDate() {
    return leaveDate;
  }

  public void setLeaveDate(String leaveDate) {
    this.leaveDate = leaveDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HumanResourcesHistory humanResourcesHistory = (HumanResourcesHistory) o;
    return Objects.equals(this.hireDate, humanResourcesHistory.hireDate) &&
        Objects.equals(this.reason, humanResourcesHistory.reason) &&
        Objects.equals(this.leaveDate, humanResourcesHistory.leaveDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hireDate, reason, leaveDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HumanResourcesHistory {\n");
    
    sb.append("    hireDate: ").append(toIndentedString(hireDate)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    leaveDate: ").append(toIndentedString(leaveDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
